apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-pineapple
spec:
  replicas: 2
  selector:
    name: update-demo
    version: pineapple
  template:
    metadata:
      labels:
        name: update-demo
        version: pineapple
    spec:
      containers:
      - image: gcr.io/google_containers/update-demo:pineapple
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
